"""
Utility functions for the hyperfield project.

This module contains helper functions for primality testing, finding primitive roots,
and prime factorization. It also contains legacy functions for working with prime
fields GF(p).
"""

def is_prime(n):
    """Check if a number is prime."""
    if n < 2:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    r = int(n**0.5)
    for i in range(3, r+1, 2):
        if n % i == 0:
            return False
    return True

def find_primitive_root(p):
    """Finds a primitive root modulo p (generator of the multiplicative group)."""
    if p == 2: return 1
    phi = p - 1
    factors = prime_factors(phi)
    for g in range(2, p):
        if all(pow(g, phi // f, p) != 1 for f in factors):
            return g
    raise ValueError("No primitive root found (should not happen for prime p)")

def prime_factors(n):
    """Returns a list of prime factors of n (without multiplicity)."""
    factors = []
    d = 2
    while d * d <= n:
        if n % d == 0:
            factors.append(d)
            while n % d == 0:
                n //= d
        d += 1 if d == 2 else 2
    if n > 1: factors.append(n)
    return factors

# =====================
# Legacy (prime field) helpers for GF(p) modulo a subgroup of (Z/pZ)^*
# =====================

def construct_subgroup(p, d, g):
    """Constructs the subgroup G of order d generated by g^{(p-1)/d} mod p."""
    step = (p - 1) // d
    h = pow(g, step, p)
    subgroup = set(pow(h, i, p) for i in range(d))
    return subgroup

def coset_representatives(p, G, g):
    """Determine coset representatives for (Z/pZ)^*/G."""
    seen = set()
    reps = []
    for i in range(1, p):
        if i in seen: continue
        coset = {(i * x) % p for x in G}
        if not any(x in seen for x in coset):
            reps.append(i)
            seen |= coset
    return reps

def element_to_coset_idx(x, G, reps, p):
    """Map an element to its coset index."""
    if x == 0: return -1
    for idx, r in enumerate(reps):
        if any((r * g) % p == x for g in G):
            return idx
    raise ValueError(f"Element {x} not found in any coset")

def hyperaddition(p, G, reps, i, j):
    """Hyperaddition of cosets reps[i], reps[j]."""
    A = {(reps[i] * g) % p for g in G}
    B = {(reps[j] * g) % p for g in G}
    zero = 0
    result = set()
    for a in A:
        for b in B:
            s = (a + b) % p
            if s == zero: result.add(-1)
            else: result.add(element_to_coset_idx(s, G, reps, p))
    return result

def build_addition_table(p, G, reps):
    """Build addition table including zero element (-1)."""
    m = len(reps)
    table = [[set() for _ in range(m + 1)] for _ in range(m + 1)]
    headers = [0] + reps
    idx_to_rep = {i: rep for i, rep in enumerate(reps)}
    idx_to_rep[-1] = 0
    for i in range(m + 1):
        for j in range(m + 1):
            if i == 0 and j == 0: table[i][j] = {0}
            elif i == 0: table[i][j] = {idx_to_rep[j-1]}
            elif j == 0: table[i][j] = {idx_to_rep[i-1]}
            else:
                result_indices = hyperaddition(p, G, reps, i-1, j-1)
                result_keys = set(idx_to_rep[idx] for idx in result_indices)
                table[i][j] = result_keys
    df_table = pd.DataFrame(table, index=[f"[{h}]" for h in headers], columns=[f"[{h}]" for h in headers])
    def format_cell(cell_set): return "{" + ",".join([f"[{e}]" for e in sorted(cell_set)]) + "}"
    df_table = df_table.map(format_cell)
    return df_table
